version: "3.9"

services:
  # Python-приложение FastAPI
  app:
    build: ./app
    container_name: fastapi_app
    ports:
      - "8000:8000"
    networks:
      - my_network
    develop:
      watch:
        # Синхронизация кода Python (быстрое обновление)
        - action: sync
          path: ./app
          target: /app
          ignore:
            - "__pycache__"
            - "*.pyc"
            - "*.log"
        # Пересборка при изменении зависимостей
        - action: rebuild
          path: ./app/requirements.txt
  # Nginx для проксирования запросов
  nginx:
    build: ./nginx
    container_name: fastapi_nginx
    depends_on:
      - app
    ports:
      - "8081:80"
    networks:
      - my_network
    develop:
      watch:
        - action: sync+restart
          path: ./nginx/nginx.conf
          target: /etc/nginx/conf.d/default.conf

networks:
  my_network:
    driver: bridge
